spring.application.name=api
server.port=8081

spring.web.error.include-stacktrace=never
spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
spring.web.error.include-exception=false

spring.web.error.whitelabel.enabled=false
