spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: api
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:chatop_db}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  web:
    error:
      include-stacktrace: never
      include-message: never
      include-binding-errors: never
      include-exception: false
      whitelabel:
        enabled: false

server:
  port: 9001
